# Generated by Django 5.0.1 on 2024-01-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpaCalc', '0002_class_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='userID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
