# Generated by Django 5.0.1 on 2024-01-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpaCalc', '0003_class_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='userID',
            field=models.CharField(max_length=200),
        ),
    ]
