# Generated by Django 5.0.1 on 2024-01-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpaCalc', '0004_alter_class_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='letterGrade',
            field=models.CharField(default='B', max_length=1),
            preserve_default=False,
        ),
    ]
