# Generated by Django 5.0.1 on 2024-01-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpaCalc', '0006_remove_class_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='credits',
        ),
    ]
